Sprint 6 solution
Cakypa217/java-kanban pull request #2
Opened 2024-07-27 21:58 UTC by Cakypa217

2024-07-27 21:59 UTC, Cakypa217 commented
Трекер задач. 3.0

2024-07-28 13:20 UTC, YazykovMikhail requested changes

2024-07-28 13:20 UTC, YazykovMikhail commented on src/ru/yandex/javacource/aldukhov/schedule/manager/InMemoryHistoryManager.java
> +    public void remove(int id) {
public void remove(int id) {
        Node node =   history.remove(id);
        if (node != null) {
            removeNode(node);
        }
    }
    
Вот так будет получше

2024-07-28 13:20 UTC, YazykovMikhail commented on src/ru/yandex/javacource/aldukhov/schedule/manager/InMemoryHistoryManager.java
> +        if (history.containsKey(id)) {
Вместо этого, просто вызывай 
remove(id);
Используй методы которые у тебя уже написаны, в нем есть проверка

2024-07-28 13:20 UTC, YazykovMikhail commented on src/ru/yandex/javacource/aldukhov/schedule/manager/InMemoryHistoryManager.java
> +        history.remove(node.task.getId());
Этот метод натсраиват ссылки после удаления, сам метод удаления это remove
Написал там комментарий как улучить. 
Тут удалять не нужно

2024-07-28 13:20 UTC, YazykovMikhail commented on src/ru/yandex/javacource/aldukhov/schedule/manager/InMemoryHistoryManager.java
> +        history.put(task.getId(), newNode);
linkLast - метод для настройки ссылок, метод добавления называется add, добавление стоит вынести в него.

2024-07-28 13:20 UTC, YazykovMikhail commented on src/ru/yandex/javacource/aldukhov/schedule/manager/InMemoryHistoryManager.java
> +    }
Получается стоит добавить
   history.put(id, tail);

2024-07-28 13:20 UTC, YazykovMikhail commented on src/ru/yandex/javacource/aldukhov/schedule/manager/InMemoryHistoryManager.java
> +        if (tail == null) {
В любом случае ты делаешь 
 tail = newNode;
 сейчас есть дублирование кода. 
 вынеси это из усовий и просто делай в конце метода, ведь это в любом случае произойдет

2024-07-28 21:23 UTC, Cakypa217 commented
Трекер задач 3.1

2024-07-29 14:16 UTC, YazykovMikhail requested changes

2024-07-29 14:16 UTC, YazykovMikhail commented on src/ru/yandex/javacource/aldukhov/schedule/manager/InMemoryHistoryManager.java
> +        history.remove(node.task.getId());
У тебя удаление уже есть в методе 
  @Override
    public void remove(int id) {
    
  Node node = history.remove(id);
  
Как писал в комментарии выше, тут удаление уже не нужно

2024-07-29 22:24 UTC, Cakypa217 commented
Решенные

2024-07-30 13:10 UTC, YazykovMikhail approved these changes

2024-08-27 20:48 UTC, merged