Sprint 7 solution in file manager
Cakypa217/java-kanban pull request #3
Opened 2024-08-12 16:08 UTC by Cakypa217

Добавление 2рой реализации менеджера, добавление метода автосохранения.

2024-08-12 19:54 UTC, YazykovMikhail requested changes
Так же стоит добавить поле TaskType taskType в задачи
или еще проще сделай метод для каждой задачи 
public TaskType getType() {
		return TaskType.TASK;
	}
который будет возвращать свой тип. 
Не зря же он есть в файле

2024-08-12 19:54 UTC, YazykovMikhail commented on src/ru/yandex/javacource/aldukhov/schedule/manager/FileBackedTaskManager.java
> +            writer.write("id,type,name,status,description,epic\n");
Вынеси хедеры в константу
Обрати внимание, что перенос строки не отнрсится к хедеру, это отделная сущность и она нужна тебе по бизнес процессу, а не прям сразу вместе с хедерами
	private static final String HEADER = "id,type,name,status,description,epic";

2024-08-12 19:54 UTC, YazykovMikhail commented on src/ru/yandex/javacource/aldukhov/schedule/manager/FileBackedTaskManager.java
> +            writer.write("id,type,name,status,description,epic\n");
Для преноса строки используй:
writer.newLine();
ведь в каждой орперационной системе перенос строки делается по своему
Поправь везде в этом методе

2024-08-12 19:54 UTC, YazykovMikhail commented on src/ru/yandex/javacource/aldukhov/schedule/manager/FileBackedTaskManager.java
> +
Можно сделать один метод, вместо этих 3:

как нибудь вот так:

```
	private String toString(Task task) {
		return task.getId() + "," + task.getType() + "," + task.getName() + "," + task.getStatus() + "," + task.getDescription() + "," + (task.getType().equals(TaskType.SUBTASK) ? ((Subtask) task).getEpicId() : "");
	}
```

2024-08-12 19:54 UTC, YazykovMikhail commented on src/ru/yandex/javacource/aldukhov/schedule/manager/FileBackedTaskManager.java
> +                Task task = new Task(name, description);
сделай дополнительные констуркторы на все нелобхомые поля и сразу создавай обьект с нужными полями, что бы потом не делать set

2024-08-12 19:54 UTC, YazykovMikhail commented on src/ru/yandex/javacource/aldukhov/schedule/manager/FileBackedTaskManager.java
> +    private void load() {
Не стоит использовать бизнес методы для добавления задач, в них же есть внутренния логикаЕ: например создание нового id, а нам нужно вернуть именно с тем, с которым мы сохранили. Поэтому стоит напрямую восстанавливать задачу в хранилище
Так же стоит вернуть сетчик идентификатора
С учетом этого метод будет выглядеть как то так:

	public static FileBackedTaskManager loadFromFile(File file) {
		final FileBackedTaskManager taskManager = new FileBackedTaskManager(file);
		try {
			final String csv = Files.readString(file.toPath());
			final String[] lines = csv.split(System.lineSeparator());
			int generatorId = 0;
			for (int i = 1; i < lines.length; i++) {
				String line = lines[i];
				if (line.isEmpty()) {
					break;
				}
				final Task task = fromString(line);
				final int id = task.getId();
				if (id > generatorId) {
					generatorId = id;
				}
				taskManager.addAnyTask(task);
			}
			for (Map.Entry<Integer, Subtask> e : taskManager.subtasks.entrySet()) {
				final Subtask subtask = e.getValue();
				final Epic epic = taskManager.epics.get(subtask.getEpicId());
				epic.addSubtaskId(subtask.getId());
			}
			taskManager.generatorId = generatorId;
		} catch (IOException e) {
			throw new ManagerSaveException("Can't read form file: " + file.getName(), e);
		}
		return taskManager;
	}

2024-08-12 19:54 UTC, YazykovMikhail commented on src/ru/yandex/javacource/aldukhov/schedule/manager/FileBackedTaskManager.java
> +    private void load() {
Предварительно сделай все поля в классе InMemoryTaskManager protected, что бы в ним был прямой доступ 
И так же понадобиться метод:
	protected void addAnyTask(Task task) {
		final int id = task.getId();
		switch (task.getType()) {
			case TASK:
				tasks.put(id, task);
				break;
			case SUBTASK:
				subtasks.put(id, (Subtask) task);
				break;
			case EPIC:
				epics.put(id, (Epic) task);
				break;
		}
	}

2024-08-23 00:06 UTC, Cakypa217 commented on src/ru/yandex/javacource/aldukhov/schedule/manager/FileBackedTaskManager.java
> +    private void load() {
Замечания исправил.

2024-08-23 00:12 UTC, Cakypa217 commented
Замечания исправил.

2024-08-23 15:05 UTC, YazykovMikhail approved these changes
Отмечай поправленные комментари как "решенные" м ревьюеру будет понятно что было поправлено, а что нет и тебе в следующем ревью будет понятно, какие актуальные коммеентарии, а какие старые

2024-08-23 15:05 UTC, YazykovMikhail commented on src/ru/yandex/javacource/aldukhov/schedule/manager/FileBackedTaskManager.java
> +    private static final String HEADER = "id,type,name,status,description,epic";
статические переменные обьявляются первыми в списке - по кодстайлу

2024-08-23 15:05 UTC, YazykovMikhail commented on src/ru/yandex/javacource/aldukhov/schedule/manager/FileBackedTaskManager.java
> +    private void load() {
Не актуальные методы удаляй сразу, а то ведь он остается в коде и придет другой разработчик и подумает что его можно использовать

2024-08-23 15:05 UTC, YazykovMikhail commented on src/ru/yandex/javacource/aldukhov/schedule/manager/InMemoryTaskManager.java
> +    protected void addAnyTask(Task task) {
этот метод лучше вынести в FileBackedTaskManager, этот метод отновится к логике восстановления файла. 
А не к базовым методам InMemoryTaskManager

2024-08-25 15:13 UTC, Cakypa217 commented on src/ru/yandex/javacource/aldukhov/schedule/manager/FileBackedTaskManager.java
> +    private static final String HEADER = "id,type,name,status,description,epic";
исправил

2024-08-25 15:14 UTC, Cakypa217 commented on src/ru/yandex/javacource/aldukhov/schedule/manager/FileBackedTaskManager.java
> +    private void load() {
исправил

2024-08-25 15:15 UTC, Cakypa217 commented on src/ru/yandex/javacource/aldukhov/schedule/manager/InMemoryTaskManager.java
> +    protected void addAnyTask(Task task) {
исправил

2024-08-27 20:48 UTC, merged